package com.saleh.tahweelati;

import android.Manifest;import android.app.*;import android.os.*;import android.content.*;import android.content.pm.PackageManager;import android.database.*;import android.database.sqlite.*;import android.graphics.Color;import android.graphics.Typeface;import android.net.Uri;import android.provider.ContactsContract;import android.text.*;import android.text.InputType;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import java.text.*;import java.util.*;

public class MainActivity extends Activity {
    EditText amount, recipient, recipientPhone, sender, senderPhone, search; TextView preview; LinearLayout historyBox; DB db;
    int blue=Color.rgb(13,71,161), green=Color.rgb(22,163,74), bg=Color.rgb(245,247,250); private static final int PICK_CONTACT=501; private boolean pickingSender=false;
    @Override public void onCreate(Bundle b){super.onCreate(b);getWindow().setStatusBarColor(blue);db=new DB(this);build();renderHistory("");}
    TextView tv(String s,float z,int c){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(c);t.setTypeface(Typeface.DEFAULT,Typeface.NORMAL);t.setPadding(0,3,0,3);return t;}
    GradientDrawable gd(int color,float r){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(r);return g;}
    EditText field(String hint){EditText e=new EditText(this);e.setHint(hint);e.setTextSize(16);e.setSingleLine(true);e.setPadding(14,0,14,0);e.setBackground(gd(Color.WHITE,18));if(hint.contains("المبلغ")||hint.contains("47,400"))e.setInputType(InputType.TYPE_CLASS_NUMBER|InputType.TYPE_NUMBER_FLAG_DECIMAL);else if(hint.contains("رقم"))e.setInputType(InputType.TYPE_CLASS_PHONE);else e.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_FLAG_CAP_SENTENCES);return e;}
    Button btn(String text,int color){Button b=new Button(this);b.setText(text);b.setTextSize(14);b.setTextColor(Color.WHITE);b.setAllCaps(false);b.setBackground(gd(color,18));b.setMinHeight(52);b.setMinimumHeight(52);b.setPadding(8,0,8,0);return b;}
    LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(16,16,16,16);l.setBackground(gd(Color.WHITE,22));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,0,0,12);l.setLayoutParams(p);return l;}
    void addField(LinearLayout c,String label,EditText e){c.addView(tv(label,13,Color.DKGRAY));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,52);p.setMargins(0,4,0,10);c.addView(e,p);}
    void addContactButton(LinearLayout c,String text,View.OnClickListener listener){Button b=btn("👤  "+text,blue);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,46);p.setMargins(0,-4,0,10);c.addView(b,p);b.setOnClickListener(listener);}
    void build(){
      ScrollView sv=new ScrollView(this);sv.setFillViewport(true);LinearLayout root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(14,14,14,22);root.setBackgroundColor(bg);sv.addView(root);setContentView(sv);
      LinearLayout head=card();head.setPadding(18,18,18,18);head.setBackground(gd(blue,24));TextView title=tv("تحويلاتي  ⇄",25,Color.WHITE);title.setTypeface(null,Typeface.BOLD);head.addView(title);head.addView(tv("إنشاء رسالة تحويل وحفظ كل عملية مع التاريخ والوقت",13,0xDDEBFFFF));root.addView(head);
      LinearLayout form=card();amount=field("مثال: 47,400");recipient=field("اسم المستلم");recipientPhone=field("رقم المستلم");sender=field("اسم المرسل");senderPhone=field("رقم المرسل");addField(form,"المبلغ الصافي",amount);addField(form,"اسم المستلم",recipient);addField(form,"رقم المستلم",recipientPhone);addContactButton(form,"استيراد المستلم من جهات الاتصال",v->pickContact(false));addField(form,"اسم المرسل",sender);addField(form,"رقم المرسل",senderPhone);addContactButton(form,"استيراد المرسل من جهات الاتصال",v->pickContact(true));root.addView(form);
      recipient.setOnFocusChangeListener((v,f)->{if(f)suggestRecipient();});sender.setOnFocusChangeListener((v,f)->{if(f)suggestSender();});
      LinearLayout out=card();out.addView(tv("الرسالة الناتجة",18,blue));preview=tv("أدخل البيانات لعرض الرسالة هنا.",17,Color.rgb(25,35,40));preview.setGravity(Gravity.RIGHT);preview.setPadding(16,16,16,16);preview.setBackground(gd(0xFFF4F8FF,18));out.addView(preview,new LinearLayout.LayoutParams(-1,-2));
      View divider=new View(this);divider.setBackgroundColor(0xFFD8E0EA);LinearLayout.LayoutParams dp=new LinearLayout.LayoutParams(-1,1);dp.setMargins(0,12,0,0);out.addView(divider,dp);
      LinearLayout row=new LinearLayout(this);row.setOrientation(LinearLayout.HORIZONTAL);row.setPadding(0,10,0,0);Button copy=btn("📋  نسخ الرسالة",blue),save=btn("حفظ العملية",green),clear=btn("مسح",0xFF64748B);row.addView(copy,new LinearLayout.LayoutParams(0,52,1));LinearLayout.LayoutParams q=new LinearLayout.LayoutParams(0,52,1);q.setMargins(8,0,0,0);row.addView(save,q);q=new LinearLayout.LayoutParams(0,52,1);q.setMargins(8,0,0,0);row.addView(clear,q);out.addView(row);root.addView(out);
      copy.setOnClickListener(v->copyMessage());save.setOnClickListener(v->save());clear.setOnClickListener(v->{amount.setText("");recipient.setText("");recipientPhone.setText("");sender.setText("");senderPhone.setText("");update();});
      TextWatcher w=new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){update();}public void afterTextChanged(Editable e){}};amount.addTextChangedListener(w);recipient.addTextChangedListener(w);recipientPhone.addTextChangedListener(w);sender.addTextChangedListener(w);
      LinearLayout hist=card();hist.addView(tv("سجل العمليات",18,blue));search=field("ابحث بالاسم أو الرقم أو المبلغ");hist.addView(search,new LinearLayout.LayoutParams(-1,52));historyBox=new LinearLayout(this);historyBox.setOrientation(LinearLayout.VERTICAL);hist.addView(historyBox);root.addView(hist);search.addTextChangedListener(new TextWatcher(){public void beforeTextChanged(CharSequence s,int a,int c,int d){}public void onTextChanged(CharSequence s,int a,int b,int c){renderHistory(s.toString());}public void afterTextChanged(Editable e){}});
    }
    void pickContact(boolean senderMode){pickingSender=senderMode;if(Build.VERSION.SDK_INT>=23&&checkSelfPermission(Manifest.permission.READ_CONTACTS)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.READ_CONTACTS},PICK_CONTACT);return;}launchContactPicker();}
    void launchContactPicker(){try{Intent i=new Intent(Intent.ACTION_PICK,ContactsContract.CommonDataKinds.Phone.CONTENT_URI);startActivityForResult(i,PICK_CONTACT);}catch(Exception e){toast("تعذر فتح جهات الاتصال");}}
    @Override public void onRequestPermissionsResult(int requestCode,String[] permissions,int[] grantResults){super.onRequestPermissionsResult(requestCode,permissions,grantResults);if(requestCode==PICK_CONTACT){if(grantResults.length>0&&grantResults[0]==PackageManager.PERMISSION_GRANTED)launchContactPicker();else toast("يلزم السماح بالوصول إلى جهات الاتصال للاستيراد");}}
    @Override protected void onActivityResult(int requestCode,int resultCode,Intent data){super.onActivityResult(requestCode,resultCode,data);if(requestCode!=PICK_CONTACT||resultCode!=RESULT_OK||data==null||data.getData()==null)return;Cursor c=null;try{c=getContentResolver().query(data.getData(),new String[]{ContactsContract.CommonDataKinds.Phone.DISPLAY_NAME,ContactsContract.CommonDataKinds.Phone.NUMBER},null,null,null);if(c!=null&&c.moveToFirst()){String name=c.getString(0),phone=c.getString(1);if(pickingSender){sender.setText(name==null?"":name);senderPhone.setText(phone==null?"":phone);sender.requestFocus();}else{recipient.setText(name==null?"":name);recipientPhone.setText(phone==null?"":phone);recipient.requestFocus();}update();toast("تم استيراد بيانات جهة الاتصال ✓");}}finally{if(c!=null)c.close();}}
    void update(){String a=amount.getText().toString().trim(),r=recipient.getText().toString().trim(),rp=recipientPhone.getText().toString().trim(),s=sender.getText().toString().trim(),sp=senderPhone.getText().toString().trim();if(a.isEmpty()&&r.isEmpty()&&rp.isEmpty()&&s.isEmpty()&&sp.isEmpty())preview.setText("أدخل البيانات لعرض الرسالة هنا.");else preview.setText(make(a,r,rp,s,sp));}
    String make(String a,String r,String rp,String s,String sp){return(a.isEmpty()?"":a)+" صافي\n\nالمستلم: "+r+"\n"+rp+"\n\nالمرسل: "+s+"\n"+sp;}
    void copyMessage(){String m=preview.getText().toString();if(m.startsWith("أدخل البيانات")){toast("أدخل البيانات أولًا");return;}((android.content.ClipboardManager)getSystemService(CLIPBOARD_SERVICE)).setPrimaryClip(ClipData.newPlainText("رسالة التحويل",m));toast("تم نسخ الرسالة ✓");}
    void save(){String a=amount.getText().toString().trim(),r=recipient.getText().toString().trim();if(a.isEmpty()||r.isEmpty()){toast("أدخل المبلغ واسم المستلم");return;}db.add(a,r,recipientPhone.getText().toString().trim(),sender.getText().toString().trim(),senderPhone.getText().toString().trim(),make(a,r,recipientPhone.getText().toString().trim(),sender.getText().toString().trim(),senderPhone.getText().toString().trim()),System.currentTimeMillis());renderHistory(search==null?"":search.getText().toString());toast("تم حفظ العملية");}
    void suggestSender(){String[] x=db.lastSender();if(sender.getText().length()==0&&x!=null){sender.setText(x[0]);senderPhone.setText(x[1]);}}
    void suggestRecipient(){String[] x=db.lastRecipient();if(recipient.getText().length()==0&&x!=null){recipient.setText(x[0]);recipientPhone.setText(x[1]);}}
    void renderHistory(String q){historyBox.removeAllViews();Cursor c=db.list(q);if(c.getCount()==0){TextView e=tv(q.isEmpty()?"لا توجد عمليات محفوظة بعد.":"لا توجد نتائج مطابقة.",14,0xFF667085);e.setGravity(Gravity.CENTER);e.setPadding(8,24,8,24);historyBox.addView(e);c.close();return;}while(c.moveToNext()){final long id=c.getLong(0);String a=c.getString(1),r=c.getString(2),rp=c.getString(3),s=c.getString(4),sp=c.getString(5);long tm=c.getLong(7);LinearLayout item=card();item.setPadding(14,12,14,12);LinearLayout top=new LinearLayout(this);top.setGravity(Gravity.CENTER_VERTICAL);TextView aa=tv(a+" صافي",18,blue);aa.setTypeface(null,Typeface.BOLD);top.addView(aa,new LinearLayout.LayoutParams(0,42,1));Button del=btn("حذف",0xFFDC2626);del.setMinWidth(70);top.addView(del,new LinearLayout.LayoutParams(78,46));item.addView(top);TextView names=tv("المستلم: "+r+"\n"+rp+"\nالمرسل: "+s+"\n"+sp,14,0xFF27313A);item.addView(names);item.addView(tv(new SimpleDateFormat("yyyy/MM/dd  HH:mm:ss",Locale.US).format(new Date(tm)),12,0xFF667085));item.setOnClickListener(v->openRecord(a,r,rp,s,sp));del.setOnClickListener(v->{new AlertDialog.Builder(this).setTitle("حذف العملية").setMessage("هل تريد حذف هذه العملية؟").setNegativeButton("إلغاء",null).setPositiveButton("حذف",(d,w)->{db.delete(id);renderHistory(search.getText().toString());}).show();});historyBox.addView(item);}c.close();}
    void openRecord(String a,String r,String rp,String s,String sp){amount.setText(a);recipient.setText(r);recipientPhone.setText(rp);sender.setText(s);senderPhone.setText(sp);update();((InputMethodManager)getSystemService(INPUT_METHOD_SERVICE)).hideSoftInputFromWindow(recipient.getWindowToken(),0);}
    void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}
    static class DB extends SQLiteOpenHelper{DB(Context c){super(c,"tahweelati.db",null,1);}public void onCreate(SQLiteDatabase d){d.execSQL("CREATE TABLE transfers(id INTEGER PRIMARY KEY AUTOINCREMENT,amount TEXT,recipient TEXT,recipientPhone TEXT,sender TEXT,senderPhone TEXT,message TEXT,created INTEGER)");}public void onUpgrade(SQLiteDatabase d,int o,int n){}void add(String a,String r,String rp,String s,String sp,String m,long t){ContentValues v=new ContentValues();v.put("amount",a);v.put("recipient",r);v.put("recipientPhone",rp);v.put("sender",s);v.put("senderPhone",sp);v.put("message",m);v.put("created",t);getWritableDatabase().insert("transfers",null,v);}Cursor list(String q){String w="";String[] args=null;if(q!=null&&!q.trim().isEmpty()){w="amount LIKE ? OR recipient LIKE ? OR recipientPhone LIKE ? OR sender LIKE ? OR senderPhone LIKE ?";String z="%"+q.trim()+"%";args=new String[]{z,z,z,z,z};}return getReadableDatabase().query("transfers",new String[]{"id","amount","recipient","recipientPhone","sender","senderPhone","message","created"},w,args,null,null,"created DESC");}void delete(long id){getWritableDatabase().delete("transfers","id=?",new String[]{String.valueOf(id)});}String[] lastSender(){Cursor c=getReadableDatabase().query("transfers",new String[]{"sender","senderPhone"},null,null,null,null,"created DESC","1");try{if(c.moveToFirst())return new String[]{c.getString(0),c.getString(1)};return null;}finally{c.close();}}String[] lastRecipient(){Cursor c=getReadableDatabase().query("transfers",new String[]{"recipient","recipientPhone"},null,null,null,null,"created DESC","1");try{if(c.moveToFirst())return new String[]{c.getString(0),c.getString(1)};return null;}finally{c.close();}}}
}
